import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author giselcarpinteiro
 */
public class QuickSort_GUI extends javax.swing.JFrame {
    
    SecQuickSort procesoSecuencial;
    ConQuickSort procesoConcurrente = new ConQuickSort();
    ArrayList array = new ArrayList();
    ArrayList array2 = new ArrayList();
    long ini;
    long fin;
    int arraySize=10000;
    
    public QuickSort_GUI() {
        initComponents();
        
        for(int i = 0; i<arraySize; i++){
            array.add((int)(Math.random()*arraySize));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ContenedorSecuencial = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonSequential = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSecTime = new javax.swing.JLabel();
        ContenedorConcurrente = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        buttonConcurrent = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtConTime = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNoElements = new javax.swing.JTextField();
        btnUpdateArray = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        ContenedorSecuencial.setBackground(new Color(204, 204, 204));
        ContenedorSecuencial.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(255, 255, 255)));
        ContenedorSecuencial.setForeground(new Color(0, 153, 153));
        ContenedorSecuencial.setMaximumSize(new java.awt.Dimension(182, 239));
        ContenedorSecuencial.setMinimumSize(new java.awt.Dimension(182, 200));
        ContenedorSecuencial.setName(""); // NOI18N
        ContenedorSecuencial.setPreferredSize(new java.awt.Dimension(182, 239));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SECUENCIAL:");

        buttonSequential.setText("Iniciar");
        buttonSequential.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSequentialActionPerformed(evt);
            }
        });

        jLabel4.setText("TIempo de ejecución:");

        txtSecTime.setText("0");

        javax.swing.GroupLayout ContenedorSecuencialLayout = new javax.swing.GroupLayout(ContenedorSecuencial);
        ContenedorSecuencial.setLayout(ContenedorSecuencialLayout);
        ContenedorSecuencialLayout.setHorizontalGroup(
            ContenedorSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorSecuencialLayout.createSequentialGroup()
                .addGroup(ContenedorSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorSecuencialLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(ContenedorSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(ContenedorSecuencialLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(txtSecTime))))
                    .addGroup(ContenedorSecuencialLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(ContenedorSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(buttonSequential))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        ContenedorSecuencialLayout.setVerticalGroup(
            ContenedorSecuencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorSecuencialLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSequential)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSecTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ContenedorConcurrente.setBackground(new Color(204, 204, 204));
        ContenedorConcurrente.setBorder(new javax.swing.border.LineBorder(new Color(255, 255, 255), 1, true));
        ContenedorConcurrente.setMinimumSize(new java.awt.Dimension(182, 200));
        ContenedorConcurrente.setPreferredSize(new java.awt.Dimension(182, 239));

        jLabel3.setText("CONCURRENTE ");

        buttonConcurrent.setText("Iniciar");
        buttonConcurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConcurrentActionPerformed(evt);
            }
        });

        jLabel5.setText("Tiempo de ejecución:");

        txtConTime.setText("0");

        javax.swing.GroupLayout ContenedorConcurrenteLayout = new javax.swing.GroupLayout(ContenedorConcurrente);
        ContenedorConcurrente.setLayout(ContenedorConcurrenteLayout);
        ContenedorConcurrenteLayout.setHorizontalGroup(
            ContenedorConcurrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorConcurrenteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonConcurrent)
                .addGap(53, 53, 53))
            .addGroup(ContenedorConcurrenteLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(ContenedorConcurrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContenedorConcurrenteLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txtConTime)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        ContenedorConcurrenteLayout.setVerticalGroup(
            ContenedorConcurrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorConcurrenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonConcurrent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContenedorSecuencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContenedorConcurrente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContenedorConcurrente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(ContenedorSecuencial, javax.swing.GroupLayout.PREFERRED_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );

        txtNoElements.setText("10000");
        txtNoElements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoElementsActionPerformed(evt);
            }
        });

        btnUpdateArray.setText("Actualizar");
        btnUpdateArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateArrayActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNoElements, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnUpdateArray)))
                .addGap(54, 54, 54))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateArray))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConcurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConcurrentActionPerformed
        array2.addAll(array);
        System.out.println("\nProceso Concurrente:");
        txtConTime.setText("Cargando...");
        ini = System.currentTimeMillis();
        procesoConcurrente.concurrentQuickSort(array2);
        fin = System.currentTimeMillis();
        System.out.println("El proceso concurrente tardo: " + String.valueOf(fin-ini) + " milisegundos" );
        txtConTime.setText(String.valueOf(fin-ini)+ "ms");
        array2.clear();
    }//GEN-LAST:event_buttonConcurrentActionPerformed

    private void buttonSequentialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSequentialActionPerformed
        array2.addAll(array);
        System.out.println("\nProceso secuencial:");
        txtSecTime.setText("Cargando...");
        ini = System.currentTimeMillis();
        ArrayList resultado = new ArrayList(procesoSecuencial.sequentialSort(array2));
        fin = System.currentTimeMillis();
        System.out.println("El proceso secuencial tardo: " + String.valueOf(fin-ini) + " milisegundos" );
        txtSecTime.setText(String.valueOf(fin-ini)+ "ms");
        array2.clear();
    }//GEN-LAST:event_buttonSequentialActionPerformed

    private void txtNoElementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoElementsActionPerformed

    }//GEN-LAST:event_txtNoElementsActionPerformed

    private void btnUpdateArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateArrayActionPerformed
        arraySize = Integer.parseInt(txtNoElements.getText());
        array.clear();
        for(int i = 0; i<arraySize; i++){
            array.add((int)(Math.random()*arraySize));
        }
    }//GEN-LAST:event_btnUpdateArrayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SecQuickSort procesoSecuencial = new SecQuickSort();
        ConQuickSort procesoConcurrente = new ConQuickSort();
        
        System.out.println("fin");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuickSort_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenedorConcurrente;
    private javax.swing.JPanel ContenedorSecuencial;
    private javax.swing.JButton btnUpdateArray;
    private javax.swing.JButton buttonConcurrent;
    private javax.swing.JButton buttonSequential;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel txtConTime;
    private javax.swing.JTextField txtNoElements;
    private javax.swing.JLabel txtSecTime;
    // End of variables declaration//GEN-END:variables
}
